### PR TITLE
Capstone Project: TvMaze

### PR DESCRIPTION
**Pull request by miltonHenschel**
- [x] Select the API you are going to use.

- [x] Build files structure for your React app.

- [x] Prepare routes and navigation in your app.

- [x] Make sure that a user can display a list of items and filter them. Data should come from the API.

- [x] Create the tests for the application.

- [x] Style your components to match the design provided.

- [x] Deploy the project and test for final details.

- [x] Record a video for your project.

- [x] Create a good README and PR description.

### CODE REVIEW

**Review by CollinsTatang — COMMENTED** [review]
Hi @miltonHenschel , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a PR that does not have your code changes to be reviewed 
        - [ ] No video presentation
        - [ ] No deployment link
        - [ ] No Acknowledgment as per project requirement
 Such a Pull Request can not be accepted for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by miltonHenschel** [comment]
Thanks for the remarks @CollinsTatang. Actually, this is the second time I'm submitting this. Please kindly checkout the suggestion from my last code reviewer: https://github.com/miltonHenschel/tvmaze-show/pull/5.

**Comment by CollinsTatang** [comment]
> Thanks for the remarks @CollinsTatang. Actually, this is the second time I'm submitting this. Please kindly checkout the suggestion from my last code reviewer: #5.

Hi @miltonHenschel 
Add all the project requirements and submit again for review remember to explain with happens in your pull request description.
 
Don't forget to add the old PR link to your explanation.

**Comment by miltonHenschel** [comment]
Thanks once more @CollinsTatang. I did just that. 🙏

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @miltonHenschel, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Descriptive `README` file ✔️ 
- Descriptive `Commit` history ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! You should record a `video` presenting the features of the project and the video contains a `clear` and `objective` description of the project in professional English, the `topic` and `purpose` of the project are made clear, the `demo` of the project, `highlighting` all the project features and `highlight` about a piece of the code the student finds interesting or is proud of making but I couldn't find your presentation video, please implement it 🙏🏼 

image

- [ ] [REQUIRED] Good job so far! You should have `unit` tests for several components of the `app` and some pure `functions` in the Redux code also App has `integration` tests using React Testing Library. You should perform a mocking data fetching and Redux Store connection 🙏🏼 

image


- [ ] [REQUIRED] Good job so far! You should follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) including correctly:

* Typography: font `face`, `size`, `weight`, `UI`
* Layout: `composition` and `space` between elements.

### Your Design
image


### [Behance Design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by miltonHenschel** [comment]
Hey @mukhammadrizooff, which mockup site helped you to come up with those beautiful pictures of site please?

**Review by christianbiring1 — APPROVED** [review]
Hi @miltonHenschel , 
# STATUS: APPROVED :tada: 
In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 
nicee

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by miltonHenschel** [comment]
Wow! Thanks very much @christianbiring1. I didn't think I woulda succeed this early. I only used 2/5 reviews. If we could accumulate the number of reviews left. 😆 🙏

**Pull request merged**
