### PR TITLE
Capstone Project: TvMaze

### PR DESCRIPTION
**Pull request by miltonHenschel**
- [x] Select the API you are going to use.

- [x] Build files structure for your React app.

- [x] Prepare routes and navigation in your app.

- [x] Make sure that a user can display a list of items and filter them. Data should come from the API.

- [ ] Create the tests for the application.

- [x] Style your components to match the design provided.

- [ ] Deploy the project and test for final details.

- [ ] Record a video for your project.

- [x] Create a good README and PR description.

### CODE REVIEW

**Review by fobadara — COMMENTED** [review]
Hi @miltonHenschel, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a lie demo link but still has. th live dem section (You are probably trying to see if you are on track. I will suggest that you remove the live demo section until your final submission), Your PR is requesting to merge from dev into main. This would be correct if it were a group project but since it is only you it should be a feature branch into dev

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by miltonHenschel** [comment]
Thanks for the reminder @fobadara. But since I have already merge into the dev branch, what do suggest that I do please?

**Comment by fobadara** [comment]
> Thanks for the reminder @fobadara. But since I have already merge into the dev branch, what do suggest that I do please?

You can create another PR from your last feaure branch into dev and submit that  instead

**Comment by miltonHenschel** [comment]
Thanks once more @fobadara. Will do! 🙏

**Comment by fobadara** [comment]
> Thanks once more @fobadara. Will do! 🙏

You are welcome

**Comment by miltonHenschel** [comment]
But I already submitted again @fobadara. I'm so stupid. Well, let's wait and see...

**Pull request closed without merging**
